# Site settings
title: StarYe Blog
SEOTitle: 星夜的博客 | starye Blog
header-img: img/home-bg.jpg
email: 488961953@qq.com
description: "这里是 @starye 的个人博客，与你一起发现更渺小的自己 | 要做一个没有梦想的闲鱼"
keyword: "星夜, starye, star, 夜,躺平,闲鱼"
url: "https://aiyiyo1.github.io"
baseurl: ""
future: true

# SNS settings
RSS: false
#weibo_username: huxpro
#zhihu_username: huxpro
github_username: ai金yo1
#twitter_username: huxpro

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true

# Gems
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
#disqus_username: hux

# Netease settings
netease_comment: false

# Analytics settings
#ba_track_id: [your track id]
#ga_track_id: "UA-49627206-1"
#ga_domain: huangxuan.me

# Sidebar settings
sidebar: true
sidebar-about-description: "躺平闲鱼一条，没有梦想"
sidebar-avatar: https://github.com/aiyiyo1.png

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page
page-mathjax: false

# Friends
friends: []

